### ISSUE TITLE
ERR_NO_RESULT: Could not extract stream for this track

### ISSUE THREAD

**Issue by Kisakay** [retrouser955/discord-player-deezer#3]
```TS
[04/10/2023 21:01:21 ERR]: ERR_NO_RESULT: Could not extract stream for this track

Error: Could not find stream source
    at _AttachmentExtractor.stream (/home/anais/Documents/GitHub/ihrz/node_modules/@discord-player/extractor/dist/index.js:1074:13)
    at /home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2502:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _ExtractorExecutionContext.run (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:1159:22)
    at async #createGenericStream (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2496:22)
    at async _GuildQueuePlayerNode.play (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2399:9)
    at async _Player.play (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:4494:9)
    at async Object.run (/home/anais/Documents/GitHub/ihrz/dist/src/Commands/music/!play.js:46:19)
    at async Object.run (/home/anais/Documents/GitHub/ihrz/dist/src/Commands/music/music.js:119:9)
    at async slashExecutor (/home/anais/Documents/GitHub/ihrz/dist/src/Events/interactionCreate.js:125:13)
```

I use NodeJS v20.7.0

```JSON
  "dependencies": {
    "@discord-player/equalizer": "^0.2.2",
    "@discord-player/extractor": "^4.3.1",
    "@discord-player/utils": "^0.2.1",
    "@discordjs/voice": "^0.16.0",
    "@mithron/deezer-music-metadata": "^1.0.3",
    "@types/crypto-js": "^4.1.1",
    "@types/express": "^4.17.17",
    "@types/js-yaml": "^4.0.5",
    "axios": "^1.4.0",
    "better-sqlite3": "^8.4.0",
    "canvas": "^2.11.2",
    "colors": "^1.4.0",
    "crypto-js": "^4.1.1",
    "date-and-time": "^3.0.2",
    "date-fns": "^2.30.0",
    "deepmerge-ts": "^5.1.0",
    "discord-backup": "^3.3.2",
    "discord-oauth2": "^2.11.0",
    "discord-player": "^6.6.4",
    "discord-player-deezer": "^1.0.0",
    "discord.js": "^14.13.0",
    "express": "^4.18.2",
    "fs": "^0.0.1-security",
    "https": "^1.0.0",
    "js-yaml": "^4.1.0",
    "mediaplex": "^0.0.6",
    "moment": "^2.29.4",
    "mongoose": "^7.3.1",
    "ms": "^3.0.0-canary.1",
    "os-utils": "^0.0.14",
    "ping": "^0.4.4",
    "process": "^0.11.10",
    "promise-mysql": "^5.2.0",
    "quick.db": "^9.1.6",
    "quickmongo": "^5.2.0",
    "serialize-javascript": "^6.0.1",
    "shelljs": "^0.8.5",
    "soundcloud-scraper": "^5.0.3",
    "sourcebin": "^5.0.0",
    "tslib": "^2.6.0",
    "typescript": "^5.1.6",
    "wait": "^0.4.2",
    "yarn": "^1.22.19",
    "youtube-ext": "^1.1.12"
  },
```
Used link: https://deezer.page.link/hseAsZ6CckGy6PjS8

Cordially,
Anaïs - Owner of iHorizon Project

**Comment by retrouser955** [comment]
[Closed](https://github.com/retrouser955/discord-player-deezer/issues/2) reopen the mentioned issue but do not open a new issue.
