### ISSUE TITLE
Could not find stream source

### ISSUE THREAD

**Issue by 0lom** [retrouser955/discord-player-deezer#4]
some songs works just fine but some song doesn't and it give me this error

```bash
Error: Could not find stream source
    at _AttachmentExtractor.stream (/home/container/node_modules/@discord-player/extractor/dist/index.js:1074:13)
    at /home/container/node_modules/discord-player/dist/index.js:2502:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _ExtractorExecutionContext.run (/home/container/node_modules/discord-player/dist/index.js:1159:22)
    at async #createGenericStream (/home/container/node_modules/discord-player/dist/index.js:2496:22)
    at async _GuildQueuePlayerNode.play (/home/container/node_modules/discord-player/dist/index.js:2399:9)
    at async _Player.play (/home/container/node_modules/discord-player/dist/index.js:4494:9)
    at async Object.run (/home/container/dist/commands/music/play.js:37:18)
    at Proxy.<anonymous> (/home/container/node_modules/discord-player/dist/index.js:711:25)
    at #throw (/home/container/node_modules/discord-player/dist/index.js:2471:80)
    at _GuildQueuePlayerNode.play (/home/container/node_modules/discord-player/dist/index.js:2415:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _Player.play (/home/container/node_modules/discord-player/dist/index.js:4494:9)
    at async Object.run (/home/container/dist/commands/music/play.js:37:18) Promise {
  <rejected> ERR_NO_RESULT: Could not extract stream for this track
  
  Error: Could not find stream source
      at _AttachmentExtractor.stream (/home/container/node_modules/@discord-player/extractor/dist/index.js:1074:13)
      at /home/container/node_modules/discord-player/dist/index.js:2502:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _ExtractorExecutionContext.run (/home/container/node_modules/discord-player/dist/index.js:1159:22)
      at async #createGenericStream (/home/container/node_modules/discord-player/dist/index.js:2496:22)
      at async _GuildQueuePlayerNode.play (/home/container/node_modules/discord-player/dist/index.js:2399:9)
      at async _Player.play (/home/container/node_modules/discord-player/dist/index.js:4494:9)
      at async Object.run (/home/container/dist/commands/music/play.js:37:18)
      at Proxy.<anonymous> (/home/container/node_modules/discord-player/dist/index.js:711:25)
      at #throw (/home/container/node_modules/discord-player/dist/index.js:2471:80)
      at _GuildQueuePlayerNode.play (/home/container/node_modules/discord-player/dist/index.js:2415:56)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _Player.play (/home/container/node_modules/discord-player/dist/index.js:4494:9)
      at async Object.run (/home/container/dist/commands/music/play.js:37:18)
}
```

this is my code 
```js
const player = new Player(client, {
    lagMonitor: 1000,
    useLegacyFFmpeg: false,
    ytdlOptions: {
        quality: "highestaudio",
        highWaterMark: 1 << 25
    }
});
import { default as DeezerExtractor } from "discord-player-deezer";
(async () => {
    await player.extractors.loadDefault();
})();
player.extractors.register(DeezerExtractor, {
    bridgeFrom: "SoundCloud",
});
```

but i don't think the problem from my code cuz like i said some songs works just fine

**Comment by retrouser955** [comment]
Can you provide me with the URL of some of the songs and also try updating to the latest version of discord-player.

**Comment by 0lom** [comment]
a lot of songs but here's one of them https://deezer.page.link/rrqybuTxNCeEurZ8A

**Comment by retrouser955** [comment]
![image](https://github.com/retrouser955/discord-player-deezer/assets/70205403/899fe269-a49a-4977-89c6-03307728e099)
This is an issue with discord-player itself as the built-in for discord-player-deezer is returning to `true`
![image](https://github.com/retrouser955/discord-player-deezer/assets/70205403/bc83b346-8733-4741-8d24-ab27f8ea4dd6)
Furthermore, the error stack provided can be tracked back to discord-player's default attachment extractor which could hint that discord-player's attachment extractor is catching the URL of the song before discord-player-deezer is.

Attempt to update discord-player and discord-player-deezer to its latest version
```bash
npm install discord-player@latest @discord-player/extractor@latest discord-player-deezer@latest
# or
yarn add discord-player@latest @discord-player/extractor@latest discord-player-deezer@latest
```

If the issue is still present, list the version of discord-player-deezer you are using.
